#!/usr/bin/env bash
# Both writers over every sample, byte for byte. There is no CLI to drive the Swift side, so a
# three-line scratch main compiles straight into a binary alongside dependency-free KSPKit.
set -o pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)" || exit 1

if ! command -v swiftc &> /dev/null; then
    echo "writer_parity: no swiftc on PATH" >&2
    exit 1
fi

scratch=swift/.build/writer-parity
writer=$scratch/kspwrite
source_file=$scratch/main.swift
mkdir -p "$scratch" || exit 1

cat > "$source_file.new" <<'SWIFT'
import Foundation

// Usage: kspwrite <in.KeyStepPro> <out.KeyStepPro>. Generated by scripts/writer_parity.sh.
let raw = try LenientJSON.load(contentsOf: URL(filePath: CommandLine.arguments[1]))
try LenientJSON.write(LenientJSON.canonical(raw), to: URL(filePath: CommandLine.arguments[2]))
SWIFT

mv "$source_file.new" "$source_file"

# Unoptimised on purpose: -O costs more in compile time than it saves over six files. Rebuilt on the
# sources' *contents*, never their timestamps -- a checkout or a stash pop restores an older mtime,
# and an mtime cache would hand this gate a binary built from code no longer on disk.
stamp=$scratch/sources.sha
current=$(cat swift/Sources/KSPKit/*.swift "$source_file" | shasum | cut -d' ' -f1)
if [[ ! -x $writer || $current != $(cat "$stamp" 2> /dev/null) ]]; then
    if ! swiftc swift/Sources/KSPKit/*.swift "$source_file" -o "$writer"; then
        rm -f "$stamp"
        echo "writer_parity: KSPKit did not compile" >&2
        exit 1
    fi
    echo "$current" > "$stamp"
fi

sandbox=$(mktemp -d) || exit 1
trap 'rm -rf "$sandbox"' EXIT

status=0
count=0
jobs=${KSP_PARITY_JOBS:-$(getconf _NPROCESSORS_ONLN 2> /dev/null || echo 4)}
for project in project_files/*.KeyStepPro; do
    count=$((count + 1))
    printf '%s\0' "$project" >> "$sandbox/projects"
done
if ! xargs -0 -P "$jobs" -I{} sh -c '"$0" "$1" "$2/swift_$(basename "$1")" || {
        echo "writer_parity: the Swift writer failed on $(basename "$1")" >&2
        exit 1
    }' "$writer" {} "$sandbox" < "$sandbox/projects"; then
    status=1
fi

# One interpreter for all six: starting it costs more than the writing does. It checks its own
# output against MCC's export on the way past, which is the half a port-to-port diff cannot see.
if ! uv run python - "$sandbox" <<'PYTHON'; then
import pathlib
import sys

from ksp.lenient_json import canonical, dump_path, load_path

sandbox = pathlib.Path(sys.argv[1])
for source in sorted(pathlib.Path("project_files").glob("*.KeyStepPro")):
    destination = sandbox / f"py_{source.name}"
    dump_path(canonical(load_path(source)), destination)

    mcc = source.read_bytes()
    if not mcc.endswith(b",\n}"):
        sys.exit(f"{source} lost MCC's trailing comma; the fix is never in that file")
    if destination.read_bytes() != mcc[:-3] + b"\n}":
        sys.exit(f"{source.name}: the Python writer no longer emits MCC's bytes minus the comma")
PYTHON
    echo "writer_parity: the Python writer disagrees with MCC" >&2
    exit 1
fi

for project in project_files/*.KeyStepPro; do
    name=$(basename "$project")
    if ! cmp "$sandbox/py_$name" "$sandbox/swift_$name"; then
        echo "writer_parity: $name differs between the two writers" >&2
        status=1
    fi
done

((status)) || echo "writer_parity: both writers agree on $count projects, and with MCC's own bytes"
exit "$status"
