#!/usr/bin/env bash
# M11's acceptance gate: the Swift writer must reproduce the Python writer's bytes.
#
# The companion to port_parity.sh, which covers the read path. Each port milestone (M8-M12) ends in
# a byte-comparison against the Python rather than in a feature, and this is M11's: the same project
# through both writers has to come out identical, byte for byte, or the port has drifted.
#
# The Swift suite already writes every sample and compares it to MCC's bytes minus the trailing
# comma, and the Python suite does the same, so the two are equal by transitivity. This says it
# directly instead, which is what catches a drift that both suites would report as their own
# problem rather than as a disagreement.
#
# The Python side is checked against MCC's own export as it writes, because a diff between the two
# ports cannot see the case where both broke the same way. Our output is then MCC's bytes minus the
# comma by the same transitivity, which is the property M11 actually claims.
#
# There is no CLI to drive: M11 deliberately added no command, and midi2ksp is M12. KSPKit takes no
# third-party dependencies, though, so three lines of scratch compile straight into a binary
# alongside it -- no package target, no entry point declared before its milestone.
set -o pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)" || exit 1

if ! command -v swiftc &> /dev/null; then
    echo "writer_parity: no swiftc on PATH" >&2
    exit 1
fi

scratch=swift/.build/writer-parity
writer=$scratch/kspwrite
source_file=$scratch/main.swift
mkdir -p "$scratch" || exit 1

cat > "$source_file.new" <<'SWIFT'
import Foundation

// Usage: kspwrite <in.KeyStepPro> <out.KeyStepPro>. Generated by scripts/writer_parity.sh.
let raw = try LenientJSON.load(contentsOf: URL(filePath: CommandLine.arguments[1]))
try LenientJSON.write(LenientJSON.canonical(raw), to: URL(filePath: CommandLine.arguments[2]))
SWIFT

mv "$source_file.new" "$source_file"

# Unoptimised on purpose: -O costs more in compile time than it saves over six files. Rebuilt when
# the sources have changed, since this runs on every Stop hook -- but keyed on their *contents*,
# never their timestamps: a checkout, a stash pop or a branch switch all restore an older mtime, and
# an mtime cache would then hand this gate a binary built from code that is no longer on disk. A
# stale green here would be worse than no gate at all.
stamp=$scratch/sources.sha
current=$(cat swift/Sources/KSPKit/*.swift "$source_file" | shasum | cut -d' ' -f1)
if [[ ! -x $writer || $current != $(cat "$stamp" 2> /dev/null) ]]; then
    if ! swiftc swift/Sources/KSPKit/*.swift "$source_file" -o "$writer"; then
        rm -f "$stamp"
        echo "writer_parity: KSPKit did not compile" >&2
        exit 1
    fi
    echo "$current" > "$stamp"
fi

sandbox=$(mktemp -d) || exit 1
trap 'rm -rf "$sandbox"' EXIT

status=0
count=0
# The six writes are independent and each one costs a 3.5 MB parse and a 3.5 MB emit, so they go
# across the cores for the reason midi_parity.sh sets out. The Python side below deliberately stays
# one interpreter -- see its own comment -- and the cmp loop after it is too cheap to be worth
# splitting. KSP_PARITY_JOBS=1 restores the serial order.
jobs=${KSP_PARITY_JOBS:-$(getconf _NPROCESSORS_ONLN 2> /dev/null || echo 4)}
for project in project_files/*.KeyStepPro; do
    count=$((count + 1))
    printf '%s\0' "$project" >> "$sandbox/projects"
done
if ! xargs -0 -P "$jobs" -I{} sh -c '"$0" "$1" "$2/swift_$(basename "$1")" || {
        echo "writer_parity: the Swift writer failed on $(basename "$1")" >&2
        exit 1
    }' "$writer" {} "$sandbox" < "$sandbox/projects"; then
    status=1
fi

# One interpreter for all six: starting it costs more than the writing does. It checks its own
# output against MCC's export on the way past, which is the half a port-to-port diff cannot see.
if ! uv run python - "$sandbox" <<'PYTHON'; then
import pathlib
import sys

from ksp.lenient_json import canonical, dump_path, load_path

sandbox = pathlib.Path(sys.argv[1])
for source in sorted(pathlib.Path("project_files").glob("*.KeyStepPro")):
    destination = sandbox / f"py_{source.name}"
    dump_path(canonical(load_path(source)), destination)

    mcc = source.read_bytes()
    if not mcc.endswith(b",\n}"):
        sys.exit(f"{source} lost MCC's trailing comma; the fix is never in that file")
    if destination.read_bytes() != mcc[:-3] + b"\n}":
        sys.exit(f"{source.name}: the Python writer no longer emits MCC's bytes minus the comma")
PYTHON
    echo "writer_parity: the Python writer disagrees with MCC" >&2
    exit 1
fi

for project in project_files/*.KeyStepPro; do
    name=$(basename "$project")
    if ! cmp "$sandbox/py_$name" "$sandbox/swift_$name"; then
        echo "writer_parity: $name differs between the two writers" >&2
        status=1
    fi
done

((status)) || echo "writer_parity: both writers agree on $count projects, and with MCC's own bytes"
exit "$status"
