"""Regenerate src/ksp/bulk_plan.py from Arturia's device descriptor.

The repository ships the facts rather than Arturia's file, so the tool works on
machines with no MCC installed. Re-run only on a firmware update, then run the
tests: they hold the generated table to the captured request stream.

The vendor file is not strict JSON. It carries trailing commas before closing
brackets, the same dialect as the project files, so it goes through
strip_trailing_commas -- not lenient_json.loads, which repairs only the single
comma before a final closing brace. Duplicate `desc` and `comment` keys are
present too and are harmless: json is last-wins already.
"""

import json
import sys
from collections.abc import Iterator
from itertools import product
from pathlib import Path
from typing import Any

from ksp.lenient_json import strip_trailing_commas

VENDOR = Path("/Library/Arturia/MIDI Control Center/Resources/KeyStepPro.json")
TARGET = Path("src/ksp/bulk_plan.py")
IDX = -1

Leaf = tuple[int, tuple[int, ...], tuple[tuple[int, ...], ...], int | None]
Group = tuple[int, int, tuple[Leaf, ...]]

HEAD = '''"""Which addresses to ask the device for, and in what order.

GENERATED by tools/gen_bulk_plan.py from Arturia's own ``bulkOperation``
descriptor. Do not edit by hand -- regenerate. Walking this table reproduces
MIDI Control Center's request stream byte-for-byte, which is what
tests/test_bulk_plan.py asserts.

A group is ``(idx_lo, idx_hi, leaves)`` and a leaf is ``(item, params, dims,
count)``. ``IDX`` inside a dimension stands for the group's current index, and
``count is None`` marks the index-less short form. Emission order is group,
index, leaf, param, then the product of the dimensions -- the device is read in
exactly that order.

The keys this plan never addresses hold literal 0 in every corpus file, so
bulk_read zero-fills them rather than spending requests to retrieve zeros
(spec section 7).
"""

from collections.abc import Iterator
from itertools import product
from typing import Final

from ksp.sysex import ReadRequest

#: Stands in for the enclosing multibulk index inside a dimension.
IDX: Final = -1

Leaf = tuple[int, tuple[int, ...], tuple[tuple[int, ...], ...], int | None]
Group = tuple[int, int, tuple[Leaf, ...]]

'''

TAIL = '''

def iter_requests() -> Iterator[ReadRequest]:
    """Every read MCC issues, in MCC's order."""
    for low, high, leaves in PLAN:
        for index in range(low, high + 1):
            for item, params, dims, count in leaves:
                if count is None:
                    for param in params:
                        yield ReadRequest(item=item, param=param, indices=(), count=None)
                    continue
                resolved = [tuple(index if v == IDX else v for v in dim) for dim in dims]
                for param in params:
                    for combination in product(*resolved):
                        yield ReadRequest(
                            item=item, param=param, indices=combination, count=count
                        )
'''


def normalise(template: list[Any]) -> tuple[int, tuple[tuple[int, ...], ...], int]:
    """One ``bulkItemId`` list into ``(item, dims, count)``."""
    item = template[0][0]
    body = list(template[1:])
    trailing: list[int] = []
    while body and isinstance(body[-1], int):
        trailing.insert(0, body.pop())

    dims: list[tuple[int, ...]] = []
    for element in body:
        if element == "IDX":
            dims.append((IDX,))
        elif isinstance(element, list):
            dims.append(tuple(IDX if v == "IDX" else v for v in element))
        else:
            raise ValueError(f"unexpected template element {element!r}")

    if len(trailing) == 2:
        start, count = trailing
        dims.append((start,))
        return item, tuple(dims), count
    return item, tuple(dims), trailing[0]


def iter_leaves(node: Any) -> Iterator[dict[str, Any]]:
    if isinstance(node, dict):
        if "bulkParamIds" in node:
            yield node
        if "multibulk" in node:
            yield from iter_leaves(node["multibulk"])
    elif isinstance(node, list):
        for child in node:
            yield from iter_leaves(child)


def build(descriptor: dict[str, Any]) -> list[Group]:
    plan: list[Group] = []
    for entry in descriptor["bulkOperation"]:
        low, high = entry.get("multibulk_idx", (0, 0))
        rows: list[Leaf] = []
        for leaf in iter_leaves(entry):
            template = leaf["bulkItemId"]
            params = tuple(leaf["bulkParamIds"])
            if isinstance(template, int):
                rows.append((template, params, (), None))
            else:
                item, dims, count = normalise(template)
                rows.append((item, params, dims, count))
        plan.append((low, high, tuple(rows)))
    return plan


def expand(plan: list[Group]) -> Iterator[tuple[int, int]]:
    """The same walk ``iter_requests`` performs, so REQUEST_COUNT cannot
    disagree with the table it describes."""
    for low, high, leaves in plan:
        for index in range(low, high + 1):
            for item, params, dims, count in leaves:
                if count is None:
                    for param in params:
                        yield item, param
                    continue
                resolved = [tuple(index if v == IDX else v for v in dim) for dim in dims]
                for param in params:
                    for _ in product(*resolved):
                        yield item, param


def render(plan: list[Group], total: int) -> str:
    body = "PLAN: Final[tuple[Group, ...]] = (\n"
    for low, high, rows in plan:
        body += f"    ({low}, {high}, (\n"
        for row in rows:
            body += f"        {row!r},\n"
        body += "    )),\n"
    body += ")\n\n#: Requests this plan expands to. MCC issued exactly this many.\n"
    body += f"REQUEST_COUNT: Final = {total}\n"
    return HEAD + body + TAIL


def main() -> int:
    if not VENDOR.is_file():
        print(f"{VENDOR} not found -- MIDI Control Center is not installed", file=sys.stderr)
        return 2
    descriptor = json.loads(
        strip_trailing_commas(VENDOR.read_text(encoding="utf-8", errors="replace"))
    )
    plan = build(descriptor)
    total = sum(1 for _ in expand(plan))
    TARGET.write_text(render(plan, total))
    print(f"wrote {TARGET}: {len(plan)} groups, {total} requests")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
